gotthardp/lorawan-server

src/lorawan_mac.erl
Hi,
There is a bug in my commit `f1b5bc1523e53a4e58e26d906bee0a68b9615225`.
For example:
```Erlang
UpLinkCounter = 66000.
FCnt = 66000 band 16#FFFF.
LocalFCnt = 65000.
%% Bug :  999 = Gap = 16#FFFF - (LocalFCnt band 16#FFFF) + FCnt.
%% Right: 
Gap = 16#10000 - (LocalFCnt band 16#FFFF) + FCnt.
```
=> fix fcnt when fcnt > 16#FFFF

src/lorawan_connector_mqtt.erl
the connector topic only works for `{group}` for example, but not for `{group}-{devwui}`. this fixes the issue.
=> fix badmatch when giving two replacements or more in connector topic

priv/admin/admin.js, src/lorawan_mac_commands.erl, src/lorawan_mac_region.erl, src/lorawan_server.app.src
This fix enables Japan's channel plan temporay.
Supposed regulation is below.
Freq: 920.6MHz - 923.4MHz (200kWHz)
Transmit power: <=20mW (13dBm)
LBT: 5msec
Duty Cycle: no limit
=> Temporary fix to enable Japan's channel plan.

doc/Integration.md
Detailed the formats and limitations of the Adafruit IO MQTT services, with an example Parse Uplink function explained.
=> Adafruit IO interface clarifications

doc/Integration.md
Adafruit IO allows simple values to be passed in MQTT instead of JSON, but given the possibility of arbitrary strings it is safer to pack them into JSON explicitly.
=> Minor changes to Adafruit IO section

.gitignore, doc/Cluster.md, lorawan_server.config, src/lorawan_db.erl
As agreed, all tables are automatically `disc_copies`, some rough documentation also in place.
=> First cluster commit

src/lorawan_sup.erl
Just to make clear, which server came up and online in a shared DB scheme.
=> Report node name in the started event.

priv/admin/admin.js, src/lorawan_admin_servers.erl, src/lorawan_db.erl
Addition of the node to cluster via web-interface is now reversed.
Now you must add new nodes to the cluster **from the master** server.
=> Reverse clustering behaviour

doc/Installation.md
Building the Debian package requires rsync.
=> Installation.md: build dependency rsync

priv/admin/admin.js
On Linux the available memory includes the buffered and cached memory.
This closes issue #520
=> admin/admin.js: correct available memory display

priv/admin/admin.js
If the height is dynamic and the timeline is empty the height is changed
every few milliseconds. This moves the text below.
This resolves issue #522.
=> admin/admin.js: constant height of timeline

lorawan_server.config, rebar.config
By adding %%-*-erlang-*- as first line in config files Vim and GNU Emacs
can identify these as Erlang based and apply correct syntax coloring.
=> config: use %%-*-erlang-*- as first line

src/lorawan_connector_http.erl
In handle_info/2 an error occurs with basic authentication due to
duplicate use of variable 'Auth'.
Closes issue #545.
Fixes: 8d2fefd8ad42 ("Issues #292,#460: Token based authentication for HTTP")
=> lorawan_connector_http: support authentication

doc/Handlers.md, src/lorawan_connector_mqtt.erl
The retain flag in the uplink message to an MQTT server signals that the
message content shall be kept and presented to any client subscribing to
the topic at a later moment.
With the patch the retain flag can be set in the uplink function of the
handler.
retain = true       - create a retained record
retain = delete     - delete the retained record and create a non-retained
record.
none or other value - create a non-retained record
To avoid sending irrelevant data the field 'retain' is removed from the
message sent to the MQTT server.
Closes #579
=> MQTT connector: retain flag

doc/Development.md
src/lorawan_server.app.src has to be updated when creating a new release,
cf. issue #555. The release tag should be signed.
=> Development.md: clarify release process

doc/Handlers.md, src/lorawan_application_backend.erl
Up to now we could only set the 'data' field via the binary return value of
the downlink function.
With the patch we allow the downlink function to return either a binary or
a map.
If a binary is returned, it is used to update the 'data' value.
If a map is returned, this map replaces the original map passed to the
downlink function. All relevant download fields like devaddr, deveui, port,
pending, receipt, and data can be set.
Here is a simple example:
fun(Vars) ->
Vars#{
deveui => <<16#3065ECFEFF6FC458:64>>,
port => 43,
data => <<16#02, 16#0113:16/little>>
}
end.
Closes #572.
=> handle_downlink: allow map returned by downlink function

src/lorawan_admin.erl, src/lorawan_connector.erl, src/lorawan_connector_mongodb.erl, src/lorawan_control.erl, src/lorawan_db_guard.erl, src/lorawan_gw_forwarder.erl, src/lorawan_http_digest.erl
One call to string:join and one call to string:right remain in the code - direct replacement with lists:join/2 and string:pad/3, as recommended, will require extra calls to lists:flatten/1. The only potential benefit of the 'recommended' function set, apart from being non-obsolete, is its inherent Unicode support.
=> Replace *some* of the obsolete string: functions

priv/admin/admin.js
Checks for the element presence should be of the form ``` 'value' in ... ```, not ```value in ...```
=> Typo in $scope.value checks in 'admin.js' Fixes #732

src/lorawan_connector_mongodb.erl
tuple_calls workaround rebar directive fails under some rare circumstances, better to remove it completely. This fixes observed cases with mongodb connector failing on some installations.
=> Eliminate tuple_calls in mongodb connector. Fixes #687

src/lorawan_db_guard.erl
According to the RFC, email addresses should be separated by a comma.
https://tools.ietf.org/html/rfc5322#section-3.6.3
This came up because I we have been trying to configure our server to send using SES and the server started crashing with the following error message: 
```
2020-11-06 16:33:34 =SUPERVISOR REPORT====
Supervisor: {local,gun_sup}
Context:    child_terminated
Reason:     {{owner_gone,{{nocatch,{permanent_failure,<<"554 Transaction failed: Illegal semicolon, not in group\r\n">>}},[{gen_smtp_client,try_DATA,4,[{file,"/lorawan-server/_build/default/lib/gen_smtp/src/gen_smtp_client.erl"},{line,333}]},{gen_smtp_client,send_it,2,[{file,"/lorawan-server/_build/default/lib/gen_smtp/src/gen_smtp_client.erl"},{line,193}]},{gen_smtp_client,send_it_nonblock,3,[{file,"/lorawan-server/_bui …
```
=> Switch email separator from ";" to ","

src/lorawan_backend_sup.erl, src/lorawan_connector_monitor.erl, src/lorawan_server.app.src
A separate gen_server sitting under backend_sup will periodically scan `connector` table for the entries failed with <<"network">> error code and attempt their restart in case it was connection problem. Only enabled connectors with **single** <<"network">> error will be considered, disabled connectors or connectors having other errors as well will not be attempted.
=> Attempt periodic restart of failed Connectors

Dockerfile
Docker container run may exhibit strange behaviour when code compiled for OTP/21 is run on default OTP/24. We must specify OTP/21 explicitly for image creation.
=> Bug in Dockerfile - must specify OTP 21 explicitly
